#ifndef Eunm_h__
#define Eunm_h__

enum MOUSEKEYSTATE { DIM_LB, DIM_RB, DIM_MB, DIM_END };
enum MOUSEMOVESTATE { DIMS_X, DIMS_Y, DIMS_Z, DIMS_END };

enum COMPONENT { COM_FRUSTUM, COM_COLLISION, COM_TRAIL, COM_END };

enum OBJ_ID { OBJ_PLAYER, OBJ_MAP, OBJ_END };

enum SCENE { SCENE_1, SCENE_2, SCENE_END};

enum ANIM {
	IDLE_RELAXED = 0, RUN = 1, ATTACK1 = 2, ATTACK2 = 3, SKILL1 = 4,
	SKILL2 = 5, IDLE = 6, GET_RESOURCE = 7, DIE = 8, END = 9,
};
//string COM_FRUSTUM = "Frustum";
#endif // Eunm_h__
